# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_flask:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        source venv/bin/activate
        pip install flask
        pip install numpy
    - name: Run Flask
      env:
        FLASK_APP: "main.py"
        FLASK_ENV: "development"
      run: |
        flask run --host=0.0.0.0 --port:5000
    - name: Keep the job running
      run: |
        sleep infinity
